### ISSUE TITLE
Backend: Breiten- und Längengrad der Entries Reihenfolge ändern

### ISSUE THREAD

**Issue by lamon4** [chribon/DHBW-Softwareprojekt#12]

**Comment by Stra1ghter** [comment]
**Das ist interessant:** leaflet braucht ```[latitude, longitude]``` also ```[Breitengrad, Längengrad]```. Geodjango / Django-Rest-Framework (-gis) nimmt standardmäßig Geojson ([und das braucht es genau anders herum, siehe 3.1.1](https://tools.ietf.org/html/rfc7946)).
[Leaflet kann Geojson direkt anzeigen](https://leafletjs.com/examples/geojson/).
Wir könnten von den einzelnen Entries jetzt auch die ```coordinates``` direkt in Leaflet als geoJson reinwerfen (das funktioniert einwandfrei).

Der Punkt ist jetzt, wir könnten das ganze richtig [GeoJSON](https://tools.ietf.org/html/rfc7946) konform machen (siehe Punkt 1.5). Dann könnten wir das vorne einfach direkt in Leaflet reinwerfen. Das würde im Sinne vom OpenData-Gedanken sein.
Andererseits müssten wir auch einiges anpassen... z.B. die Models und Fixture-Daten.
ABER: dank [rest_framework_gis (siehe ```GeoFeatureModelSerializer```)](GeoFeatureModelSerializer) geht das sehr einfach!

@kela4 was meinst du?

**Comment by kela4** [comment]
Alles, was näher an den OpenData Gedanken vertritt, finde ich gut. Seh ich das richtig, dass das abändern dann mehr Fleiß- als Denkarbeit ist? 
Hast du das schon testweise ausprobiert @Stra1ghter?

**Comment by Stra1ghter** [comment]
@kela4 Ich habs noch nicht ausprobiert, aber aktuell nehmen wir ja den rest_framework_serializer, und benutzen die rest_framework_gis App gar nicht. [Das hat das eingebaut und serialisiert GeoJSON raus (siehe README - Punkt GeoFeatureModelSerializer)](https://github.com/openwisp/django-rest-framework-gis).

Dann wäre unser System standardkonform und es würde wesentlich besser zu OpenData passen. Ich schau mal wie stark der Aufwand zur Anpassung wirklich ist. Ich wäre aber generell auch erstmal dafür. Kommt denk ich auch bei der Präsentation sehr gut an, ist halt ein wirklicher Standard den wir da einhalten, somit wäre es auch mit anderen GIS kompatibel.

**Comment by Stra1ghter** [comment]
Da ist ja echt super einfach...lol... Ich bin absolut dafür dass so zu machen. Das ist Standardkonform heißt
1. es lässt sich super einfach mit anderen GIS integrieren.
2. ist ein super Punkt für die Präsentation später.
