### ISSUE TITLE
Backend: "openingHours" und "prices" von Entries allgemein in "info" umbenennen

### ISSUE THREAD

**Issue by lamon4** [chribon/DHBW-Softwareprojekt#14]

**Comment by Stra1ghter** [comment]
Haben wir besprochen und wir haben das ER-Modell extra so gemacht. Es geht darum, dass wir die ganzen Daten maschinenlesbar haben und das auch so (Open Data) so anbieten können. Dann kann man das ganze am Ende auch weiter spinnen und sagen man gewinnt neue Daten. Z.B. kann man nach Wertbereichen filtern etc. etc.. Das geht aber nur wenn wir weitere konkrete Attribute per Typ der Einträge haben.

**Comment by lamon4** [comment]
Ich brauch für mein typescript objekt eine feste Bezeichnung. Unterschiedliche Namen funktioniert nicht.

**Comment by kela4** [comment]
Zu dem Punkt müssen wir uns mal zusammensetzen. Die Idee war ja auch, dass die Einträge teilweise unterschiedlich viele verschiedene Info-Einträge haben. Kannst du die Anzeige diese Infos auf später schieben @lamon4 und wir überlegen dann gemeinsam, wie das umgesetzt wird? Müssen ja auch noch für die Unterkategorien definieren, welche Infos diese alle haben.

**Comment by Stra1ghter** [comment]
Da beißt uns Typescript in den Fuß... [Leaflet kann GeoJSON nativ, und man kann auch die Punkte aus den Properties anreichern](https://leafletjs.com/examples/geojson/).

Imo haben wir zwei gute Ansätze:
1) Typescript ist ja ein Javascript superset, also sollte das auch mit einfachen Typescript Objekten gehen (also keine eigenen Types für die JSON-Objekte der API verwenden, sondern stinknormale Objekte... falls das wirklich geht), dann schmeißen wir halt da mal den Vorteil von Typescript weg. Sehe da bei uns aktuell aber auch keinen Vorteil drinn...
2) Wir können jeweils eigene Models für jeden Eintragstyp (Glassmüll, Grundrichtwerte, ...) erstellen. Wenn wir das jetzt GeoJSON konform machen, brauchen wir die eigenen Models jeweils nur für die properties der FeatureCollection

**Comment by lamon4** [comment]
Zu 1.: Ich benutze einfache Typescript Objekte. Das ändert nichts daran, dass ein Attribut des Objekts nicht mal "openingHours" und manchmal "prices" heißen kann. Wenn ich den API Response auf das Objekt abbilde müssen die Namen des Attribute übereinstimmen, sonst gibt der Aufruf des Attributes später nichts zurück.

**Comment by Stra1ghter** [comment]
Ich hab mal ein Beispiel-Setup zum Holen von GeoJSON in 737bff888b8e6866dba5ae3d0d8c54800ea07cd3 eingefügt (schreibt das Ergebnis als JSON ins Impressum).

Und das geht mit den Attributen, es geht in Typescript (hier bietet sich Vererbung an, siehe mein commit). Angular mappt das auch direkt auf die richtigen Typen. (Probier mal mein Beispiel mit subcagetory 7 oder 1 aus, dann siehst du das).
Wir könnten es aber auch dynamisch typisiert lösen, wie [Leaflet das gemacht hat, siehe Link > Option > style 2tes Beispiel](https://leafletjs.com/examples/geojson/). Dazu musst du dann halt dynamisch  die Properties holen, siehe [Javascript in operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in).

**Comment by lamon4** [comment]
@Stra1ghter danke für das Beispiel. Leider ist es an meinem Problem vorbei programmiert. Auch in deinem Beispiel sind die Attributs-Namen immer gleich. Außerdem geht es um Properties nicht um die Geometry (Geometry ist auch ohne Vererbung kein Problem).
Ich habe jetzt einfach einzeln überprüft welche Properties existieren und darauf entsprechend gehandelt (ähnliche Vorgehensweise wie mit "in" operator)

**Comment by Stra1ghter** [comment]
@lamon4 Das Beispiel ging ja nicht um properties, sondern um das GeoJSON setup. Aber wie ich das mit den Geometry gemacht hab, geht das genauso bei den properties. Ich hab mein Beispiel mal um **type-safe** ```properties``` ergänzt, siehe 8e16757baaa651173196dfa8ec6a7cd58b82aa72.

**Comment by lamon4** [comment]
@Stra1ghter das Setup für die GeoJSON gab es schon^^.  Des mit den Properties würde funktionieren, ist jedoch nicht besonders praktikabel, da ich ja die Properties mit z.B, "as GroundValueProperty" erst casten müsste (wenn ich dein Beispiel richtig verstanden habe). Dafür müsste ich ja erst festellen, dass die Properties da sind bzw. fehlen. Nur um auf die info-text property zuzugreifen lohnt sich das nicht.
Ich habe es so gelöst:

if (feature.properties.openingHours) {
                if (feature.properties.openingHours.length > 0) {
                  _this.info = feature.properties.openingHours.toString();
                }
              }

**Comment by Stra1ghter** [comment]
Da gabs keine FreatureCollection und auch nur einen festen Typ "coordinate" der spätestens bei Polygonen als Antwort nicht funktioniert hätte.

Downcasten muss man natürlich, wenn man das typsicher nutzen will. Der Compiler kann ja nicht wissen was zur Laufzeit kommt. Aber das kann man anhan der id machen. Oder wir geben noch den Eintragstyp explizit der subcategory mit. Die Properties muss man dafür nicht anfassen.

Wir müssen uns sowieso nochmal besprechen wegen den Eintragstypen... laut Angabe wollen sie auch andere Daten wie timeseries o.ä.
